general:
  t_stop: 604800  # the stop time for the simulation (sec) 1hour=3600, 1day=86400, 1week=604800, 1month=2.628e+6 (suggested: 604800)
  t_tran: 80000  # the transient time (sec) (suggested: 70000)
  n_batch: 64  # the number of batches (suggested: 64)
  t_sample: 100  # the sampling interval (sec) (suggested: 100)
  confidence: 0.95  # the level of confidence (suggested: 0.95)
  random:
    generator: "MarcianiMultiStream"  # the class name of the random generator
    seed: 123456789  # the initial seed for the random generator

tasks:
  arrival_rate_1: 6.00  # the arrival rate for tasks of type 1 (tasks/s)
  arrival_rate_2: 6.25  # the arrival rate for tasks of type 2 (tasks/s)

system:
  cloudlet:
    n_servers: 20  # the number of servers
    service_rate_1: 0.45  # the service rate for tasks of type 1 (tasks/s)
    service_rate_2: 0.27  # the service rate for tasks of type 2 (tasks/s)
    threshold: 20  # the occupancy threshold
    server_selection: "ORDER"  # the server-selection rule

  cloud:
    service_rate_1: 0.25  # the service rate for tasks of type 1 (tasks/s).
    service_rate_2: 0.22  # the service rate for tasks of type 2 (tasks/s).
    t_setup_mean: 0.8  # the mean setup time to restart a task in the Cloud (s).
